"""initial schema

Revision ID: 57bbee2ccda2
Revises:
Create Date: 2026-08-31 19:59:39.086652

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "57bbee2ccda2"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sources",
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column(
            "platform", sa.Enum("instagram", "youtube", name="platform", native_enum=False, length=20), nullable=False
        ),
        sa.Column("handle_or_channel", sa.String(length=255), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum("recording", "qa_insight", "podcast_insight", name="sourcetype", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("source_id"),
    )
    op.create_table(
        "taxonomy_entries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("dimension", sa.String(length=100), nullable=False),
        sa.Column("value", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dimension", "value", name="uq_taxonomy_dimension_value"),
    )
    op.create_table(
        "media_items",
        sa.Column("media_id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("published_date", sa.DateTime(), nullable=True),
        sa.Column("duration_sec", sa.Float(), nullable=True),
        sa.Column("raw_media_path", sa.String(length=1000), nullable=True),
        sa.Column(
            "ingestion_status",
            sa.Enum(
                "pending",
                "downloading",
                "downloaded",
                "transcribing",
                "transcribed",
                "tagging",
                "ready",
                "failed",
                "needs_review",
                name="ingestionstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.source_id"],
        ),
        sa.PrimaryKeyConstraint("media_id"),
        sa.UniqueConstraint("url"),
    )
    op.create_table(
        "transcripts",
        sa.Column("transcript_id", sa.String(length=36), nullable=False),
        sa.Column("media_id", sa.String(length=36), nullable=False),
        sa.Column("full_text", sa.Text(), nullable=False),
        sa.Column("language", sa.String(length=10), nullable=True),
        sa.Column("transcription_method", sa.String(length=100), nullable=False),
        sa.Column("transcription_confidence", sa.Float(), nullable=True),
        sa.Column("transcribed_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["media_id"],
            ["media_items.media_id"],
        ),
        sa.PrimaryKeyConstraint("transcript_id"),
        sa.UniqueConstraint("media_id"),
    )
    op.create_table(
        "validation_issues",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("media_id", sa.String(length=36), nullable=False),
        sa.Column("rule_id", sa.String(length=10), nullable=False),
        sa.Column("message", sa.String(length=1000), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["media_id"],
            ["media_items.media_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "segments",
        sa.Column("segment_id", sa.String(length=36), nullable=False),
        sa.Column("transcript_id", sa.String(length=36), nullable=False),
        sa.Column(
            "speaker",
            sa.Enum("saad", "prospect", "host", "unknown", name="speaker", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("start_ms", sa.Integer(), nullable=False),
        sa.Column("end_ms", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("segment_type", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["transcript_id"],
            ["transcripts.transcript_id"],
        ),
        sa.PrimaryKeyConstraint("segment_id"),
    )
    op.create_table(
        "tags",
        sa.Column("tag_id", sa.String(length=36), nullable=False),
        sa.Column("segment_id", sa.String(length=36), nullable=False),
        sa.Column("tag_dimension", sa.String(length=100), nullable=False),
        sa.Column("tag_value", sa.String(length=100), nullable=False),
        sa.Column(
            "tagged_by", sa.Enum("human", "claude_auto", name="taggedby", native_enum=False, length=20), nullable=False
        ),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("reviewed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["segment_id"],
            ["segments.segment_id"],
        ),
        sa.PrimaryKeyConstraint("tag_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tags")
    op.drop_table("segments")
    op.drop_table("validation_issues")
    op.drop_table("transcripts")
    op.drop_table("media_items")
    op.drop_table("taxonomy_entries")
    op.drop_table("sources")
    # ### end Alembic commands ###
